name: Build Signed APK

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Decode keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > keystore.jks

      - name: Grant permission for gradlew
        run: chmod +x ./gradlew

      - name: Build signed APK
        run: ./gradlew :app:assembleRelease
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Rename APK with build number
        run: |
          mkdir -p output
          cp app/build/outputs/apk/release/app-release.apk output/TeleVip-${{ github.run_number }}.apk

      - name: Show SHA256
        run: sha256sum output/*.apk

      - name: Upload signed APK
        uses: actions/upload-artifact@v4
        with:
          name: TeleVip-${{ github.run_number }}.apk
          path: output/*.apk
